name: deploy

on:
  push:
    # Action run will only be triggered on updates to master branch
    branches:
      - main

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out git repository
      - name: checkout
        uses: actions/checkout@master

      # Install dependencies
      - name: dependencies
        run: sudo apt-get update && sudo apt-get install ruby-full build-essential zlib1g-dev tree -y && sudo gem install jekyll bundler

      # Build Jekyll site
      - name: build
        run: |
          ls && cd locksmith && bundle install && bundle exec jekyll build && ls && ls _site

      - name: move
        run: |
          sudo mkdir /site && sudo mv locksmith/_site/* /site/ && sudo rm -rf locksmith/* && sudo cp -r /site/* locksmith/
  

      - name: GIT
        run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"
      
      - name: GIT
        run:   ls && cd locksmith && git checkout -b pages && git add -f .  && git commit -m 'Site built' 
        
      - name: GIT
        run: git push -f origin pages 